import { useEffect } from "react";

/**
 * Dečiji režim - the HOME-SCREEN identity (icon + name) of the installed app.
 *
 * The kid shell and the grown-up app are one deployment behind one `index.html`,
 * so out of the box a child installing from `/kid/*` would get the parent app's
 * blue "Porodični Asistent" tile. There is no single switch for this, because
 * the two platforms read two different places:
 *
 * - Android / Chrome takes the name and icons from the WEB APP MANIFEST
 *   (`<link rel="manifest">`, generated by vite-plugin-pwa from `vite.config.ts`).
 * - iOS Safari IGNORES the manifest icons entirely. "Add to Home Screen" reads
 *   `<link rel="apple-touch-icon">` and `<meta name="apple-mobile-web-app-title">`
 *   out of the live document at the moment the user taps it.
 *
 * So this swaps BOTH, on entering the kid shell, and puts the grown-up values
 * back on the way out - otherwise a parent who leaves a child's preview and
 * installs their own app would end up with a kid-branded parent tile.
 *
 * IMPORTANT, and not a bug to chase: this only affects NEW installs. An app
 * that is already on a home screen keeps the icon and name it was installed
 * with; neither platform re-reads them for an existing install. A family that
 * installed before this shipped has to remove the tile and add it again.
 *
 * The URLs are all relative to `BASE_URL`, and `public/kid.webmanifest` is
 * written entirely in manifest-relative URLs (`"kid"`, `"kid-192x192.png"`),
 * which resolve against the MANIFEST's own URL. That is what makes one static
 * file correct both in dev (served at `/`) and on GitHub Pages (served under
 * `/family-assistant-react/`) with no build-time templating.
 */

/** Matches `name` / `short_name` in `public/kid.webmanifest`. */
const KID_APP_TITLE = "Moj dan";

const KID_MANIFEST = "kid.webmanifest";
const KID_APPLE_ICON = "kid-apple-touch-icon-180x180.png";

/**
 * Where a swapped element parks the grown-up app's value until it is restored.
 * Keeping it on the element rather than in a module variable means the swap is
 * idempotent and self-describing: two applies in a row (React StrictMode) can
 * never overwrite the original with a kid value, because it is only recorded
 * when it is not already there.
 */
const RESTORE_ATTR = "data-app-value";

/** `rel` parked on the iOS splash links while the kid identity is on. */
const DISABLED_STARTUP_IMAGE_REL = "kid-disabled-apple-touch-startup-image";

function withBase(file: string): string {
  return `${import.meta.env.BASE_URL}${file}`;
}

function swapAttribute(element: Element | null, attribute: string, next: string): void {
  if (!element) return;
  if (!element.hasAttribute(RESTORE_ATTR)) {
    element.setAttribute(RESTORE_ATTR, element.getAttribute(attribute) ?? "");
  }
  element.setAttribute(attribute, next);
}

function restoreAttribute(element: Element | null, attribute: string): void {
  const previous = element?.getAttribute(RESTORE_ATTR);
  if (!element || previous === null || previous === undefined) return;
  element.setAttribute(attribute, previous);
  element.removeAttribute(RESTORE_ATTR);
}

/**
 * Put the kid app's install identity on the document, or hand it back (`false`).
 *
 * Exported alongside the hook for the same reason `applyKidThemeToDom` is: it
 * is a plain DOM write with no React in it, and being able to call it directly
 * is what makes it testable.
 */
export function applyKidInstallIdentityToDom(enabled: boolean): void {
  if (typeof document === "undefined") return;
  const head = document.head;

  const manifest = head.querySelector('link[rel="manifest"]');
  const appleIcon = head.querySelector('link[rel="apple-touch-icon"]');
  const title = head.querySelector('meta[name="apple-mobile-web-app-title"]');

  if (enabled) {
    swapAttribute(manifest, "href", withBase(KID_MANIFEST));
    swapAttribute(appleIcon, "href", withBase(KID_APPLE_ICON));
    swapAttribute(title, "content", KID_APP_TITLE);

    // The `apple-touch-startup-image` set in index.html is the grown-up app's
    // blue splash, and iOS would happily use it for the kid app too. There is
    // no kid equivalent on purpose (that set is ~30MB), so take the links out
    // of play and let iOS fall back to the manifest `background_color`, which
    // is the icon's own teal - the launch then reads as one solid screen.
    for (const link of head.querySelectorAll('link[rel="apple-touch-startup-image"]')) {
      swapAttribute(link, "rel", DISABLED_STARTUP_IMAGE_REL);
    }
    return;
  }

  restoreAttribute(manifest, "href");
  restoreAttribute(appleIcon, "href");
  restoreAttribute(title, "content");
  for (const link of head.querySelectorAll(`link[rel="${DISABLED_STARTUP_IMAGE_REL}"]`)) {
    restoreAttribute(link, "rel");
  }
}

/**
 * Wear the kid app's install identity for as long as `enabled` holds, and give
 * the document back to the grown-up app on unmount or when it goes false.
 *
 * Mounted once, by the `kid` layout route - and deliberately NOT enabled on
 * `/kid/pregled`: that is a parent looking at a child's app from their own
 * session, so what they would install is still their own app.
 */
export function useKidInstallIdentity(enabled: boolean): void {
  useEffect(() => {
    if (!enabled) return;
    applyKidInstallIdentityToDom(true);
    return () => applyKidInstallIdentityToDom(false);
  }, [enabled]);
}
